export * as fuelCreate from './handlers/fuel-create';
export * as fuelList from './handlers/fuel-list';
export * as health from './handlers/health';
export * as me from './handlers/me';
export * as migrate from './handlers/migrate';
export * as vehiclesCreate from './handlers/vehicles-create';
export * as vehiclesGet from './handlers/vehicles-get';
export * as vehiclesList from './handlers/vehicles-list';
export * as vehiclesUpdate from './handlers/vehicles-update';
